cloud:
  eureka-host: localhost
  processing-service-url: http://localhost:8082
  currency-service-url: http://localhost:8085

spring:
  application:
    name: api-gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: currency-rate-service
          uri: ${cloud.currency-service-url}
          predicates:
            - Path=/api/v1/currency/**
        - id: exchange-processing-service-url
          uri: ${cloud.processing-service-url}
          predicates:
            - Path=/api/v1/user/**, /api/v1/account/**


server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://${cloud.eureka-host}:8761/eureka/